### ISSUE TITLE
Cannot get the result when running on CLI 

### ISSUE THREAD

**Issue by shivaluma** [wxh06/dockerjudge#20]
![image](https://user-images.githubusercontent.com/33391636/86250487-d63fee00-bbda-11ea-896e-fbe13c0386ef.png)

Hi, i see that your project is really great but i cant receive the result while running sample code on the CLI.
Currently im using macos Catalina. And is there anyway can i create a web api using this project.
Im new to python so please help.
Thank you.

**Comment by wxh06** [comment]
Try to run `docker ps` after calling the `judge` function to check the container status.
If it's up, just wait a few seconds.

**Comment by wxh06** [comment]
It may take a little time to start the container.

**Comment by wxh06** [comment]
I'm gonna close this issue if this isn't a bug.
